remote_theme: cotes2020/jekyll-theme-chirpy

lang: ko

timezone: Asia/Seoul

title: Tech Blog
tagline: "개발 에러 분석 & 기술 블로그"

description: >-
  개발 중 만나는 에러를 분석하고 해결법을 공유하는 기술 블로그입니다.

url: "https://hayeon-kimm.github.io"
baseurl: "/aicp_techblog"

github:
  username: Hayeon-kimm

social:
  name: Hayeon Kim
  links:
    - https://github.com/Hayeon-kimm

# Web Analytics
analytics:
  google:
    id: ""

# Preferences
theme_mode: dark

avatar: ""

toc: true

comments:
  provider: ""

assets:
  self_host:
    enabled: false

paginate: 10

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _tabs
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
